# Generated by Django 4.1.5 on 2023-01-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('shows', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BannerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='banners.banner')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='banners.category')),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ManyToManyField(through='banners.BannerCategory', to='banners.category'),
        ),
    ]
